// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1eB8luVPlQF07Anx2YGwl99nSAolh84Q',
    appId: '1:151340523557:web:cd54c9f4ed3a90978ddfcc',
    messagingSenderId: '151340523557',
    projectId: 'shadowcv',
    authDomain: 'shadowcv.firebaseapp.com',
    storageBucket: 'shadowcv.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJyB7fZ8Y7s4kCr09IH_U7ABwQthzh9_M',
    appId: '1:151340523557:android:3044b2ec702fdfef8ddfcc',
    messagingSenderId: '151340523557',
    projectId: 'shadowcv',
    storageBucket: 'shadowcv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr3S736LBgz9O_Ogb1erxK6LlmmaCJnR8',
    appId: '1:151340523557:ios:07ca294d480e65e38ddfcc',
    messagingSenderId: '151340523557',
    projectId: 'shadowcv',
    storageBucket: 'shadowcv.firebasestorage.app',
    iosBundleId: 'com.example.shadowcv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr3S736LBgz9O_Ogb1erxK6LlmmaCJnR8',
    appId: '1:151340523557:ios:07ca294d480e65e38ddfcc',
    messagingSenderId: '151340523557',
    projectId: 'shadowcv',
    storageBucket: 'shadowcv.firebasestorage.app',
    iosBundleId: 'com.example.shadowcv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1eB8luVPlQF07Anx2YGwl99nSAolh84Q',
    appId: '1:151340523557:web:2966378e4b0478168ddfcc',
    messagingSenderId: '151340523557',
    projectId: 'shadowcv',
    authDomain: 'shadowcv.firebaseapp.com',
    storageBucket: 'shadowcv.firebasestorage.app',
  );
}
